app_name = "lpm"
master_core = 0
duration = 3000

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "00:06.0"
    cores = [1]

[[ports]]
    name = "eth2"
    device = "00:07.0"
    cores = [1]
